# Generated by Django 3.2.4 on 2021-07-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedores',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='vendedores',
            name='apellidoPaterno',
        ),
    ]
