# Generated by Django 3.2.4 on 2021-07-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0002_auto_20210714_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='is_activo',
            field=models.BooleanField(null=True),
        ),
    ]
