# Generated by Django 3.2.4 on 2021-07-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0003_alter_transacciones_is_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='transaccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='publicidad.transacciones'),
            preserve_default=False,
        ),
    ]
