# Generated by Django 3.2.4 on 2021-07-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0004_detalle_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='transaccion',
        ),
    ]
